### ISSUE TITLE
Sign up email confirmation links to empty heroku domain not actual domain

### ISSUE THREAD

**Issue by lortza** [tekHudson/tekkedout-dnd-tools#11]
When I click the `Confirm my account` link in the confirmation email, the link points to "https://teks-dnd-tools.herokuapp.com..." not "https://dnd.tekkedout.net...". Also Google thinks that's highly suspicious. 
<img width="634" alt="screenshot 2017-07-21 08 23 05" src="https://user-images.githubusercontent.com/8680712/28465371-1bc4ccd6-6dee-11e7-8704-1ab97e132432.png">

**Comment by tekHudson** [comment]
This was an issue with an environment variable.

It has been resolved. Thanks for the heads up 👍

**Comment by tekHudson** [comment]
Please use https://dnd.tekkedout.net/users/confirmation/new to receive a newly generated email.

**Comment by lortza** [comment]
Oh, I already circumvented it by manually entering the intended url. 😉  

Also - :man_facepalming: of *course* it was an environment variable. I was looking everywhere in the codebase for where it was defined and just couldn't figure out the magic.

**Comment by tekHudson** [comment]
This is determined by `config.action_mailer.default_url_options ` in config\environment\production.rb
